---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/sibemo33/public_html/almoxarifado.sibem.top/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/rm -f $DEPLOYPATH/bootstrap/cache/*.php
    - /bin/rm -f $DEPLOYPATH/storage/framework/views/*.php
    - /usr/local/bin/php $DEPLOYPATH/artisan migrate --force || true
    - /usr/local/bin/php $DEPLOYPATH/artisan optimize:clear || true

